version: "3.8"

services:
  rai-db:
    image: postgres:15-bullseye
    container_name: rai-db
    environment:
      - POSTGRES_DB=rai
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - dbdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  rai-api:
    build: .
    container_name: rai-api-container
    image: rai-api-img
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"
      - "9229:9229"
      - "5555:5555"
    env_file:
      - .env
    volumes:
      - ./:/rai-api/
      - node_modules:/app/node_modules

volumes:
  dbdata: {}
  node_modules: {}
